### PR TITLE
My edits

### PR DESCRIPTION
**Pull request by startergo**
Add debug=0x144 as a requirement for gfxutil.

### CODE REVIEW

**Comment by startergo** [comment]
Automatic reset changed my main branch to match yours as you changed it. Not sure now how can we merge the change as your branch is ahead.

**Comment by dakanji** [comment]
Needs discussion ... What is this for?
Maybe best to have an issue raised first ahead of such.

**Comment by startergo** [comment]
> 
> 
> Needs discussion ... What is this for?
> Maybe best to have an issue raised first ahead of such.
> 
> Also seems to include unrelated items.

https://gist.github.com/joevt/e3cd4ff08aae06279134969c98ca3ab7

> Setup: In macOS, using Sierra or later, nvram boot-args must have at least the following debug=0x144. If it does not, then:
sudo nvram boot-args="debug=0x144 ... other contents of boot-args here ..."
This may require SIP to be disabled, otherwise execute the command without sudo in Recovery's Terminal.app.

this is requirement for gfxutil

**Comment by dakanji** [comment]
Use case seems a bit too narrow/limited.

A better target is to allow arbitrary boot argument strings.

Will create a separate issue for that

**Pull request closed without merging**
